[package]
name = "chatyk"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
axum = { version = "0.8.4", features = [
    "http2",
    "macros",
    "multipart",
    "query",
    "tracing",
    "ws",
] }
dotenvy = "0.15.7"
diesel = { version = "2.1.3", features = ["chrono", "postgres", "r2d2"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = [
    "rt-multi-thread",
    "macros",
    "rt",
    "tracing",
    "signal",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = [
    "serde",
    "tracing",
    "chrono",
] }
chrono = "0.4.42"
snowflake = "1.3.0"
once_cell = "1.21.3"
bcrypt = "0.17.1"
r2d2 = "0.8.10"
r2d2_postgres = "0.18.2"
axum-macros = "0.5.0"
jsonwebtoken = "9.3.1"
cookie = "0.18.1"
